[workspace]
members = ["runtime", "usbmidi-host"]
resolver = "2"

[profile.dev]
debug = true
#opt-level = "z"
panic = "unwind"

[profile.release]
opt-level = "z"
debug = false
lto = true
panic = "abort"
