[package]
name = "sync-thumbv6m"
version = "0.2.0"
authors = ["Francis Lalonde"]
edition = "2021"
description = ""
license = "MIT OR Apache-2.0"

[dependencies]
atomic-polyfill = "0.1"
crossbeam-utils = { version = "0.8", default-features = false }
heapless = "0.7"

